spring.application.name=HelpHands-Mail
server.port=8081

# Base configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/help_hands_mail?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
logging.level.org.hibernate.persister.entity=ERROR

#Email Sender configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=helphands.contact@gmail.com
spring.mail.password=gcth lnve owni fvml
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true